#!/usr/bin/env bash
# =============================================================================
# sync-content.sh — Pull markdown docs from all quarkloop product repos
# =============================================================================
# Clones each product repository with --depth 1 (shallow, no history) and
# copies their documentation markdown into content/docs/<section>/ for the
# Fuma Docs build to consume.
#
# The content/ directory is gitignored — it is regenerated by this script
# on every build. The source of truth for each doc file lives in its
# product repo.
#
# Usage:
#   ./scripts/sync-content.sh
#
# Prerequisites:
#   - git
#   - curl (for fetching raw files if git clone fails)
# =============================================================================

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

CONTENT_DIR="content/docs"
TMP_DIR="${TMP_DIR:-/tmp/quark-docs-sync}"

# Product repos and their doc locations
# Uses SSH URLs for auth with deployed SSH keys. For CI/CD (Vercel, GitHub Actions),
# either make the repos public and switch to HTTPS URLs, or inject a deploy key.
declare -A REPOS=(
    ["quark"]="git@github.com:quarkloop/quark.git"
    ["quark-js"]="git@github.com:quarkloop/quark-js.git"
    ["runtime"]="git@github.com:quarkloop/poc-rust-runtime.git"
    ["agent"]="git@github.com:quarkloop/agent.git"
)

echo "=== Quark Docs — Content Sync ==="
echo ""

# Clean previous content
echo "→ Cleaning previous content..."
rm -rf "$CONTENT_DIR"
mkdir -p "$CONTENT_DIR"

# Clean tmp
rm -rf "$TMP_DIR"
mkdir -p "$TMP_DIR"

# ─── 1. Quark Platform (MDX content) ─────────────────────────────────────
echo ""
echo "→ Cloning quarkloop/quark (platform docs)..."
git clone --depth 1 "${REPOS[quark]}" "$TMP_DIR/quark" 2>&1 | tail -1

mkdir -p "$CONTENT_DIR/platform"
# The quark repo has Fuma-formatted MDX files in docs/content/docs/
if [ -d "$TMP_DIR/quark/docs/content/docs" ]; then
    cp "$TMP_DIR/quark/docs/content/docs/"*.mdx "$CONTENT_DIR/platform/" 2>/dev/null || true
    # Use the quark repo's meta.json if it exists, otherwise we'll create one
    if [ -f "$TMP_DIR/quark/docs/content/docs/meta.json" ]; then
        cp "$TMP_DIR/quark/docs/content/docs/meta.json" "$CONTENT_DIR/platform/meta.json"
    fi
fi
echo "  ✓ Copied $(ls "$CONTENT_DIR/platform/"*.mdx 2>/dev/null | wc -l) MDX files to platform/"

# ─── 2. Quark JS SDK ─────────────────────────────────────────────────────
echo ""
echo "→ Cloning quarkloop/quark-js (SDK docs)..."
git clone --depth 1 "${REPOS[quark-js]}" "$TMP_DIR/quark-js" 2>&1 | tail -1

mkdir -p "$CONTENT_DIR/sdk"
if [ -d "$TMP_DIR/quark-js/docs" ]; then
    for f in "$TMP_DIR/quark-js/docs/"*.md; do
        [ -f "$f" ] || continue
        # Lowercase the filename for URL consistency
        lower=$(basename "$f" | tr '[:upper:]' '[:lower:]')
        cp "$f" "$CONTENT_DIR/sdk/$lower"
    done
fi
echo "  ✓ Copied $(ls "$CONTENT_DIR/sdk/"*.md 2>/dev/null | wc -l) MD files to sdk/"

# ─── 3. Quark Runtime (Rust PoC) ─────────────────────────────────────────
echo ""
echo "→ Cloning quarkloop/poc-rust-runtime (runtime docs)..."
git clone --depth 1 "${REPOS[runtime]}" "$TMP_DIR/runtime" 2>&1 | tail -1

mkdir -p "$CONTENT_DIR/runtime"
if [ -d "$TMP_DIR/runtime/docs" ]; then
    for f in "$TMP_DIR/runtime/docs/"*.md; do
        [ -f "$f" ] || continue
        # Lowercase the filename for URL consistency
        lower=$(basename "$f" | tr '[:upper:]' '[:lower:]')
        cp "$f" "$CONTENT_DIR/runtime/$lower"
    done
fi
echo "  ✓ Copied $(ls "$CONTENT_DIR/runtime/"*.md 2>/dev/null | wc -l) MD files to runtime/"

# ─── 4. Quark Agent ──────────────────────────────────────────────────────
echo ""
echo "→ Cloning quarkloop/agent (agent docs)..."
git clone --depth 1 "${REPOS[agent]}" "$TMP_DIR/agent" 2>&1 | tail -1

mkdir -p "$CONTENT_DIR/agent"
# Agent repo has docs in docs/ and root-level .md files
if [ -d "$TMP_DIR/agent/docs" ]; then
    for f in "$TMP_DIR/agent/docs/"*.md; do
        [ -f "$f" ] && cp "$f" "$CONTENT_DIR/agent/"
    done
fi
# Also copy key root-level docs (lowercase to avoid conflicts with README)
for f in ARCHITECTURE.md DEVELOPMENT.md SPACE-CONFIG.md RELEASE.md; do
    if [ -f "$TMP_DIR/agent/$f" ]; then
        # Lowercase the filename for URL consistency
        lower=$(echo "$f" | tr '[:upper:]' '[:lower:]' | sed 's/\.md$/.md/')
        cp "$TMP_DIR/agent/$f" "$CONTENT_DIR/agent/$lower"
    fi
done
echo "  ✓ Copied $(ls "$CONTENT_DIR/agent/"*.md 2>/dev/null | wc -l) MD files to agent/"

# ─── Create section meta.json files ──────────────────────────────────────
echo ""
echo "→ Creating section meta.json files..."

# Top-level meta.json — defines the four sections
cat > "$CONTENT_DIR/meta.json" <<'EOF'
{
  "title": "Documentation",
  "pages": [
    "---Platform---",
    "platform",
    "---SDK---",
    "sdk",
    "---Runtime---",
    "runtime",
    "---Agent---",
    "agent"
  ]
}
EOF

# Platform section meta.json (if not already copied from quark repo)
if [ ! -f "$CONTENT_DIR/platform/meta.json" ]; then
    cat > "$CONTENT_DIR/platform/meta.json" <<'EOF'
{
  "title": "Platform",
  "pages": [
    "---Concepts---",
    "abstraction",
    "design",
    "---Specification---",
    "node-uri",
    "node-catalog",
    "node-layout",
    "declaration",
    "node",
    "---Guides---",
    "environment-bootstrap",
    "cli",
    "user-story"
  ]
}
EOF
fi

# SDK section meta.json
cat > "$CONTENT_DIR/sdk/meta.json" <<'EOF'
{
  "title": "Quark JS SDK",
  "pages": [
    "architecture",
    "api",
    "build"
  ]
}
EOF

# Runtime section meta.json
cat > "$CONTENT_DIR/runtime/meta.json" <<'EOF'
{
  "title": "Quark Runtime",
  "pages": [
    "architecture",
    "abi",
    "build",
    "nats-subject-contract"
  ]
}
EOF

# Agent section meta.json — dynamically list available files
AGENT_PAGES=$(ls "$CONTENT_DIR/agent/"*.md 2>/dev/null | xargs -I{} basename {} .md | grep -v "^meta$" | sort)
AGENT_PAGES_JSON=$(echo "$AGENT_PAGES" | python3 -c "
import sys, json
pages = [line.strip() for line in sys.stdin if line.strip()]
print(json.dumps(pages, indent=2))
")
cat > "$CONTENT_DIR/agent/meta.json" <<EOF
{
  "title": "Quark Agent",
  "pages": $AGENT_PAGES_JSON
}
EOF

# ─── Inject frontmatter into .md files that lack it ──────────────────────
echo ""
echo "→ Injecting frontmatter into plain .md files..."

python3 <<'PY'
import os
import re
import json
from pathlib import Path

CONTENT = Path("content/docs")

# Map section → nice title for each known file
TITLE_OVERRIDES = {
    "sdk/architecture.md": "Architecture",
    "sdk/api.md": "API Reference",
    "sdk/build.md": "Build & Development",
    "runtime/architecture.md": "Architecture",
    "runtime/abi.md": "Node ABI Reference",
    "runtime/build.md": "Build & Development",
    "runtime/nats-subject-contract.md": "Wire Protocol (NATS Subjects)",
    "agent/running-and-debugging.md": "Running & Debugging",
    "agent/services.md": "Services",
    "agent/architecture.md": "Architecture",
    "agent/development.md": "Development",
    "agent/space-config.md": "Space Configuration",
    "agent/release.md": "Release Readiness",
}

for md_file in CONTENT.rglob("*.md"):
    rel = md_file.relative_to(CONTENT).as_posix()
    text = md_file.read_text()

    # Skip if already has frontmatter
    if text.startswith("---"):
        continue

    # Determine title
    if rel in TITLE_OVERRIDES:
        title = TITLE_OVERRIDES[rel]
    else:
        # Extract from first H1
        m = re.search(r'^#\s+(.+)$', text, re.MULTILINE)
        if m:
            title = m.group(1).strip()
            # Remove markdown formatting
            title = re.sub(r'[*`_]', '', title)
        else:
            # Fallback: filename
            title = md_file.stem.replace("-", " ").replace("_", " ").title()

    # Prepend frontmatter
    frontmatter = f"---\ntitle: \"{title}\"\ndescription: \"\"\n---\n\n"
    md_file.write_text(frontmatter + text)
    print(f"  ✓ {rel} → title: \"{title}\"")

PY

# ─── Cleanup ─────────────────────────────────────────────────────────────
echo ""
echo "→ Cleaning up temporary clones..."
rm -rf "$TMP_DIR"

# ─── Summary ─────────────────────────────────────────────────────────────
echo ""
echo "=== Sync complete ==="
echo ""
echo "Content structure:"
find "$CONTENT_DIR" -type f | sort | sed 's/^/  /'
echo ""
echo "Total files: $(find "$CONTENT_DIR" -type f | wc -l)"
