#!/usr/bin/env bash
# =============================================================================
# sync-content.sh — Pull markdown docs from all quarkloop product repos
# =============================================================================
# Clones each product repository with --depth 1 (shallow, no history) and
# copies ALL markdown files (.md, .mdx) from each repo's docs/ directory
# into content/docs/<section>/ for the Fuma Docs build to consume.
#
# The content/ directory is gitignored — it is regenerated by this script
# on every build. The source of truth for each doc file lives in its
# product repo.
#
# This script does NOT hardcode any filenames. It copies whatever .md
# and .mdx files exist in each repo's docs/ directory. If a meta.json
# file exists in docs/, it is copied as well; otherwise one is generated
# from the available files.
#
# Usage:
#   ./scripts/sync-content.sh
# =============================================================================

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

CONTENT_DIR="content/docs"
TMP_DIR="${TMP_DIR:-/tmp/quark-docs-sync}"

# Product repos: section name → git URL
# Each repo's docs/ directory will be copied to content/docs/<section>/
declare -A REPOS=(
    ["platform"]="git@github.com:quarkloop/quark.git"
    ["sdk"]="git@github.com:quarkloop/quark-js.git"
    ["agent"]="git@github.com:quarkloop/agent.git"
)

echo "=== Quark Docs — Content Sync ==="
echo ""

# Clean previous content
echo "→ Cleaning previous content..."
rm -rf "$CONTENT_DIR"
mkdir -p "$CONTENT_DIR"

# Clean tmp
rm -rf "$TMP_DIR"
mkdir -p "$TMP_DIR"

# ─── Sync each repo ──────────────────────────────────────────────────────
for section in "${!REPOS[@]}"; do
    repo_url="${REPOS[$section]}"
    echo ""
    echo "→ Cloning $repo_url → $section/"

    # Clone with --depth 1 (shallow, no history)
    git clone --depth 1 "$repo_url" "$TMP_DIR/$section" 2>&1 | tail -1

    # Create the section directory
    mkdir -p "$CONTENT_DIR/$section"

    # Copy all .md and .mdx files from the repo's docs/ directory
    # If the repo has docs/ → copy from there
    # If the repo has docs/content/docs/ (legacy Fuma layout) → copy from there
    src_dir=""
    if [ -d "$TMP_DIR/$section/docs" ]; then
        if [ -d "$TMP_DIR/$section/docs/content/docs" ]; then
            src_dir="$TMP_DIR/$section/docs/content/docs"
        else
            src_dir="$TMP_DIR/$section/docs"
        fi
    fi

    if [ -z "$src_dir" ]; then
        echo "  ⚠ No docs/ directory found in $section — skipping"
        continue
    fi

    # Copy all markdown files (.md and .mdx)
    file_count=0
    for f in "$src_dir"/*.md "$src_dir"/*.mdx; do
        [ -f "$f" ] || continue
        # Lowercase the filename for URL consistency
        lower=$(basename "$f" | tr '[:upper:]' '[:lower:]')
        cp "$f" "$CONTENT_DIR/$section/$lower"
        file_count=$((file_count + 1))
    done

    # Copy meta.json if it exists (for sidebar organization)
    if [ -f "$src_dir/meta.json" ]; then
        cp "$src_dir/meta.json" "$CONTENT_DIR/$section/meta.json"
    fi

    # Copy subdirectories if any exist (for organized docs structures)
    find "$src_dir" -mindepth 1 -maxdepth 1 -type d | while read -r subdir; do
        subdir_name=$(basename "$subdir")
        mkdir -p "$CONTENT_DIR/$section/$subdir_name"
        find "$subdir" -name '*.md' -o -name '*.mdx' | while read -r mdfile; do
            rel_path="${mdfile#$src_dir/}"
            lower=$(basename "$mdfile" | tr '[:upper:]' '[:lower:]')
            dest="$CONTENT_DIR/$section/$(dirname "$rel_path")/$lower"
            mkdir -p "$(dirname "$dest")"
            cp "$mdfile" "$dest"
        done
    done

    echo "  ✓ Copied $file_count markdown files to $section/"
done

# ─── Generate top-level meta.json ─────────────────────────────────────────
echo ""
echo "→ Generating top-level meta.json..."

# List sections alphabetically, excluding meta.json
sections=$(find "$CONTENT_DIR" -mindepth 1 -maxdepth 1 -type d | sort | xargs -I{} basename {})
pages_json=$(echo "$sections" | python3 -c "
import sys, json
sections = [line.strip() for line in sys.stdin if line.strip()]
pages = []
for s in sections:
    # Add a separator before each section (except the first)
    if pages:
        pages.append(f'---{s.title()}---')
    pages.append(s)
print(json.dumps(pages, indent=2))
")

cat > "$CONTENT_DIR/meta.json" <<EOF
{
  "title": "Documentation",
  "pages": $pages_json
}
EOF

# ─── Generate section meta.json if missing ────────────────────────────────
echo ""
echo "→ Generating section meta.json files where missing..."

for section_dir in "$CONTENT_DIR"/*/; do
    [ -d "$section_dir" ] || continue
    section_name=$(basename "$section_dir")

    if [ ! -f "$section_dir/meta.json" ]; then
        # Generate a meta.json listing all .mdx files alphabetically
        pages=$(find "$section_dir" -maxdepth 1 -name '*.mdx' | sort | xargs -I{} basename {} .mdx)
        pages_json=$(echo "$pages" | python3 -c "
import sys, json
pages = [line.strip() for line in sys.stdin if line.strip()]
print(json.dumps(pages, indent=2))
")

        cat > "$section_dir/meta.json" <<EOF
{
  "title": "${section_name^}",
  "pages": $pages_json
}
EOF
        echo "  ✓ Generated meta.json for $section_name"
    else
        echo "  ✓ Using existing meta.json for $section_name"
    fi
done

# ─── Inject frontmatter into .md files that lack it ──────────────────────
echo ""
echo "→ Injecting frontmatter into markdown files that lack it..."

python3 <<'PY'
import re
from pathlib import Path

CONTENT = Path("content/docs")

for md_file in CONTENT.rglob("*.md"):
    text = md_file.read_text()

    # Skip if already has frontmatter
    if text.startswith("---"):
        continue

    # Extract title from first H1
    m = re.search(r'^#\s+(.+)$', text, re.MULTILINE)
    title = m.group(1).strip() if m else md_file.stem.replace("-", " ").title()
    title = re.sub(r'[*`_]', '', title)

    # Prepend frontmatter
    frontmatter = f'---\ntitle: "{title}"\ndescription: ""\n---\n\n'
    md_file.write_text(frontmatter + text)
    print(f"  ✓ {md_file.relative_to(CONTENT)} → title: \"{title}\"")

# Also check .mdx files
for md_file in CONTENT.rglob("*.mdx"):
    text = md_file.read_text()

    if text.startswith("---"):
        continue

    m = re.search(r'^#\s+(.+)$', text, re.MULTILINE)
    title = m.group(1).strip() if m else md_file.stem.replace("-", " ").title()
    title = re.sub(r'[*`_]', '', title)

    frontmatter = f'---\ntitle: "{title}"\ndescription: ""\n---\n\n'
    md_file.write_text(frontmatter + text)
    print(f"  ✓ {md_file.relative_to(CONTENT)} → title: \"{title}\"")

PY

# ─── Cleanup ─────────────────────────────────────────────────────────────
echo ""
echo "→ Cleaning up temporary clones..."
rm -rf "$TMP_DIR"

# ─── Summary ─────────────────────────────────────────────────────────────
echo ""
echo "=== Sync complete ==="
echo ""
echo "Content structure:"
find "$CONTENT_DIR" -type f | sort | sed 's/^/  /'
echo ""
echo "Total files: $(find "$CONTENT_DIR" -type f | wc -l)"
